project_id="YOUR GCP PROJECT ID"
region="GCP REGION"
sa_email_to_impersonate="ADMIN ACCOUNT EMAIL ADDRESS FOR YOUR ORG"
domain="DOMAIN YOU WANT TO MANAGE"
# Run hourly
cron_schedule="0 1 * * *"
# Pick starting values for uid/gid for autogenerated accounts
start_uid = "30000"
start_gid = "30000"